-- Enable Row Level Security
alter default privileges in schema public grant all on tables to service_role;

-- 1. Create Documents Table
create table documents (
  id uuid default gen_random_uuid() primary key,
  path text not null unique,
  last_updated timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table documents enable row level security;

-- 2. Create Updates Table (for Yjs deltas)
create table updates (
  id bigint generated by default as identity primary key,
  document_id uuid references documents(id) on delete cascade not null,
  update_blob bytea not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table updates enable row level security;

-- 3. Create RLS Policies
-- IMPORTANT: For self-hosted single-user setup, we allow 'anon' role access
-- This works because:
-- 1. Your Anon Key is kept secret in plugin settings
-- 2. Data is encrypted client-side before sending
-- 3. The database only sees encrypted blobs

-- Drop old policies if they exist
drop policy if exists "Enable all access for authenticated users" on "documents";
drop policy if exists "Enable all access for authenticated users" on "updates";

-- Create new policies for anon access
create policy "Enable all access for anon users" on "documents"
as permissive for all
to anon
using (true)
with check (true);

create policy "Enable all access for anon users" on "updates"
as permissive for all
to anon
using (true)
with check (true);

-- IMPORTANT: You must enable Realtime for the 'updates' table in your Supabase Dashboard!
-- Database -> Publications -> supabase_realtime -> Toggle 'updates' ON
